#ifndef MAIN_H
#define MAIN_H

/* FIXME: replace with proper enum entry when moving upstream */
#define SNDRV_HWDEP_IFACE_HOLOPLOT_PCI	100

/* Hardware limits */
#define BUFFER_BYTES_MAX	SZ_1M
#define PERIOD_BYTES_MIN	32
#define PERIOD_BYTES_MAX	(BUFFER_BYTES_MAX / 2)
#define PERIODS_MIN		2
#define PERIODS_MAX		(BUFFER_BYTES_MAX / PERIOD_BYTES_MIN)

/* ... */
#define REMOTE_EGRESS_SOURCE	0xe8000000

/* Registers mapped on BAR0 */
#define REG_AXIPCIE_MAIN_BASE		0x8000

#define REG_AXIPCIE_INGRESS_BASE(X)	(0x8800 + (X)*0x20)
#define REG_AXIPCIE_INGRESS_CONTROL	0x08
#define REG_AXIPCIE_INGRESS_SRC_ADDR_LO	0x10
#define REG_AXIPCIE_INGRESS_SRC_ADDR_HI	0x14
#define REG_AXIPCIE_INGRESS_DST_ADDR_LO 0x18
#define REG_AXIPCIE_INGRESS_DST_ADDR_HI 0x1c

#define REG_AXIPCIE_EGRESS_BASE(X)	(0x8c00 + (X)*0x20)
#define REG_AXIPCIE_EGRESS_CONTROL	0x08
#define REG_AXIPCIE_EGRESS_CONTROL_ACTIVE	BIT(0)
#define REG_AXIPCIE_EGRESS_SRC_ADDR_LO	0x10
#define REG_AXIPCIE_EGRESS_SRC_ADDR_HI	0x14
#define REG_AXIPCIE_EGRESS_DST_ADDR_LO	0x18
#define REG_AXIPCIE_EGRESS_DST_ADDR_HI	0x1c

#define DMA_CHANNEL_CAPTURE		0
#define DMA_CHANNEL_PLAYBACK		1
#define DMA_CHANNEL_MISC_READ		2
#define DMA_CHANNEL_MISC_WRITE		3

#define MISC_INTERRUPT_INIT_DONE	0xabab0000
#define MISC_INTERRUPT_REPLY		0xabab0001

#define MISC_TRANSACTION_TIMEOUT	msecs_to_jiffies(1000)

#define REG_DMA_CHANNEL_BASE(X)			((X)*0x80)
#define REG_DMA_CHANNEL_SCRATCH_0		0x50
#define REG_DMA_CHANNEL_SCRATCH_1		0x54
#define REG_DMA_CHANNEL_SCRATCH_2		0x58
#define REG_DMA_CHANNEL_SCRATCH_3		0x5c
#define REG_DMA_CHANNEL_PCIE_INTERRUPT_STATUS	0x64
#define REG_DMA_CHANNEL_AXI_IRQ_CONTROL		0x68
#define REG_DMA_CHANNEL_AXI_INTERRUPT_ASSERT	0x74





/* Registers mapped on BAR2 */
#define REG_CC_CAPTURE_CONTROL			0x00
#define REG_CC_CAPTURE_CONTROL_RUN		BIT(0)
#define REG_CC_CAPTURE_CONTROL_RESET		BIT(1)
#define REG_CC_CAPTURE_SRC_ADDR			0x08
#define REG_CC_CAPTURE_BUFFER_SIZE		0x10
#define REG_CC_CAPTURE_PERIOD_SIZE		0x18
#define REG_CC_CAPTURE_POSITION			0x20

#define REG_CC_PLAYBACK_CONTROL			0x30
#define REG_CC_PLAYBACK_CONTROL_RUN		BIT(0)
#define REG_CC_PLAYBACK_CONTROL_RESET		BIT(1)
#define REG_CC_PLAYBACK_SRC_ADDR		0x38
#define REG_CC_PLAYBACK_BUFFER_SIZE		0x40
#define REG_CC_PLAYBACK_PERIOD_SIZE		0x48
#define REG_CC_PLAYBACK_POSITION		0x50

#define REG_BAR2_DESIGN_TYPE_AND_VERSION	0x60
#define DESIGN_TYPE_MASK			0xff
#define DESIGN_TYPE_SHIFT			0
#define DESIGN_VERSION_MASK			0xff00
#define DESIGN_VERSION_SHIFT			8

#define REG_BAR2_DEVICE_ID			0x68


#endif