#ifndef MAIN_H
#define MAIN_H

/* FIXME: replace with proper enum entry when moving upstream */
#define SNDRV_HWDEP_IFACE_HOLOPLOT_PCI	100

/* Hardware limits */
#define BUFFER_BYTES_MAX	SZ_1M
#define PERIOD_BYTES_MIN	32
#define PERIOD_BYTES_MAX	(BUFFER_BYTES_MAX / 2)
#define PERIODS_MIN		2
#define PERIODS_MAX		(BUFFER_BYTES_MAX / PERIOD_BYTES_MIN)

/* ... */
#define REMOTE_EGRESS_SOURCE	0xe8000000

/* Registers mapped on BAR0 */
#define REG_AXIPCIE_MAIN_BASE		0x8000

#define REG_AXIPCIE_INGRESS_BASE(X)	(0x8800 + (X)*0x20)
#define REG_AXIPCIE_INGRESS_CONTROL	0x08
#define REG_AXIPCIE_INGRESS_SRC_ADDR_LO	0x10
#define REG_AXIPCIE_INGRESS_SRC_ADDR_HI	0x14
#define REG_AXIPCIE_INGRESS_DST_ADDR_LO 0x18
#define REG_AXIPCIE_INGRESS_DST_ADDR_HI 0x1c

#define REG_AXIPCIE_EGRESS_BASE(X)	(0x8c00 + (X)*0x20)
#define REG_AXIPCIE_EGRESS_CONTROL	0x08
#define REG_AXIPCIE_EGRESS_SRC_ADDR_LO	0x10
#define REG_AXIPCIE_EGRESS_SRC_ADDR_HI	0x14
#define REG_AXIPCIE_EGRESS_DST_ADDR_LO	0x18
#define REG_AXIPCIE_EGRESS_DST_ADDR_HI	0x1c

#define REG_DMA_IRQ_0_STATUS		0x64
#define REG_DMA_IRQ_1_STATUS		0xe4

/* Registers mapped on BAR2 */
#define REG_CC_CAPTURE_CONTROL			0x00
#define REG_CC_CAPTURE_CONTROL_RUN		BIT(0)
#define REG_CC_CAPTURE_CONTROL_RESET		BIT(1)
#define REG_CC_CAPTURE_SRC_ADDR			0x08
#define REG_CC_CAPTURE_BUFFER_SIZE		0x10
#define REG_CC_CAPTURE_PERIOD_SIZE		0x18
#define REG_CC_CAPTURE_POSITION			0x20

#define REG_CC_PLAYBACK_CONTROL			0x30
#define REG_CC_PLAYBACK_CONTROL_RUN		BIT(0)
#define REG_CC_PLAYBACK_CONTROL_RESET		BIT(1)
#define REG_CC_PLAYBACK_SRC_ADDR		0x38
#define REG_CC_PLAYBACK_BUFFER_SIZE		0x40
#define REG_CC_PLAYBACK_PERIOD_SIZE		0x48
#define REG_CC_PLAYBACK_POSITION		0x50

#define REG_BAR2_DESIGN_TYPE_AND_VERSION	0x60
#define REG_BAR2_DEVICE_ID			0x68

#endif